const mockProjects = [
  {
    title: "Renovation of Meadows Park Playground",
    location: "The Meadows, Edinburgh",
    district: "South-East",
    author: "Alice Robertson",
    dateSubmitted: "2024-02-05",
    category: "Playground Modernization",
    excerpt: "A complete overhaul of the children’s playground in The Meadows to include new equipment, safety surfaces, and accessible features for children with disabilities.",
    content: "This project aims to renovate the aging playground at The Meadows...",
    estimatedCost: "£150,000",
    benefits: ["Improved safety", "Accessibility for all children", "Modern play experience"],
    votes: 1245
  },
  {
    title: "Parkour and Street Workout Park at Holyrood Park",
    location: "Holyrood Park, Edinburgh",
    district: "South-East",
    author: "John Murray",
    dateSubmitted: "2024-01-25",
    category: "Recreational Facility",
    excerpt: "Creation of a street workout and parkour area in Holyrood Park...",
    content: "The project proposes the construction of a parkour and street workout park...",
    estimatedCost: "£80,000",
    benefits: ["Promotes physical fitness", "Free and accessible to all", "Encourages outdoor activities"],
    votes: 967
  },
  {
    title: "Cycle Lane Expansion on Leith Walk",
    location: "Leith Walk, Edinburgh",
    district: "North-East",
    author: "Sarah MacDonald",
    dateSubmitted: "2024-02-10",
    category: "Road Infrastructure",
    excerpt: "Expanding and improving the cycle lanes along Leith Walk...",
    content: "Leith Walk is one of the busiest roads in Edinburgh...",
    estimatedCost: "£120,000",
    benefits: ["Increased cyclist safety", "Promotes eco-friendly transportation", "Reduces traffic congestion"],
    votes: 1543
  },
  {
    title: "Community Garden in Inverleith Park",
    location: "Inverleith Park, Edinburgh",
    district: "North-West",
    author: "James Stewart",
    dateSubmitted: "2024-01-15",
    category: "Green Space Development",
    excerpt: "A new community garden in Inverleith Park...",
    content: "This project proposes the creation of a community garden...",
    estimatedCost: "£45,000",
    benefits: ["Promotes sustainability", "Builds community", "Encourages healthy eating"],
    votes: 1087
  },
  {

    title: "Revitalization of Water of Leith Walkway",
    location: "Water of Leith Walkway, Edinburgh",
    district: "North-West",
    author: "Emily Campbell",
    dateSubmitted: "2024-02-01",
    category: "Pathway and Public Space Improvement",
    excerpt: "Restoration and enhancement of the Water of Leith Walkway...",
    content: "The Water of Leith Walkway is a cherished route for walkers...",
    estimatedCost: "£100,000",
    benefits: ["Increased safety", "Accessibility for all users", "Improved public space"],
    votes: 1354
  },
  {
    title: "Skatepark Construction in Sighthill",
    location: "Sighthill Park, Edinburgh",
    district: "South-West",
    author: "Michael Taylor",
    dateSubmitted: "2024-01-20",
    category: "Youth Facilities",
    excerpt: "Building a modern skatepark in Sighthill Park...",
    content: "Sighthill is in need of more youth-oriented public spaces...",
    estimatedCost: "£90,000",
    benefits: ["Engages local youth", "Encourages outdoor activities", "Safe space for recreational sports"],
    votes: 874
  },
  {
    title: "Renovation of Fountainbridge Community Centre",
    location: "Fountainbridge, Edinburgh",
    district: "South-West",
    author: "Helen Douglas",
    dateSubmitted: "2024-01-30",
    category: "Community Infrastructure",
    excerpt: "Renovating the Fountainbridge Community Centre...",
    content: "The Fountainbridge Community Centre is a hub for local residents...",
    estimatedCost: "£75,000",
    benefits: ["Supports community events", "Modern, functional spaces", "Increases participation in local activities"],
    votes: 925
  },
  {
    title: "Lighting and Path Improvement for Arthur's Seat Trails",
    location: "Arthur's Seat, Edinburgh",
    district: "South-East",
    author: "Paul Scott",
    dateSubmitted: "2024-02-12",
    category: "Pathway Enhancement",
    excerpt: "Improving the lighting and pathway surfaces on Arthur's Seat trails...",
    content: "This project proposes the installation of low-impact lighting along the primary trails of Arthur’s Seat...",
    estimatedCost: "£110,000",
    benefits: ["Increased safety", "Improved accessibility", "Eco-friendly lighting"],
    votes: 1023
  },
  {
    title: "New Basketball Courts in Leith Links",
    location: "Leith Links, Edinburgh",
    district: "North-East",
    author: "David Hamilton",
    dateSubmitted: "2024-02-08",
    category: "Sports Facility",
    excerpt: "Building new public basketball courts at Leith Links...",
    content: "This project will create two outdoor basketball courts at Leith Links...",
    estimatedCost: "£60,000",
    benefits: ["Free public sports facility", "Encourages youth sports participation", "Promotes community interaction"],
    votes: 989
  },
  {
    title: "Edinburgh City Library Digital Upgrade",
    location: "Edinburgh Central Library",
    district: "South-East",
    author: "Fiona MacLeod",
    dateSubmitted: "2024-01-28",
    category: "Cultural and Educational Infrastructure",
    excerpt: "A digital upgrade to Edinburgh Central Library...",
    content: "The Central Library has been a cornerstone of education and culture in Edinburgh...",
    estimatedCost: "£85,000",
    benefits: ["Modernized learning spaces", "Increased digital accessibility", "Promotes education and job training"],
    votes: 1157
  },
  {
    title: "Improved Drainage System in Stockbridge",
    location: "Stockbridge, Edinburgh",
    district: "North-West",
    author: "George Clarke",
    dateSubmitted: "2024-02-05",
    category: "Infrastructure",
    excerpt: "Installing an improved drainage system in Stockbridge...",
    content: "Stockbridge has faced issues with flooding during heavy rains...",
    estimatedCost: "£120,000",
    benefits: ["Flood prevention", "Improved infrastructure", "Eco-friendly water management"],
    votes: 1143
  },
  {
    title: "Dog-Friendly Zones in Princes Street Gardens",
    location: "Princes Street Gardens, Edinburgh",
    district: "South-East",
    author: "Laura Fraser",
    dateSubmitted: "2024-01-31",
    category: "Public Space Enhancement",
    excerpt: "Creating designated dog-friendly zones in Princes Street Gardens...",
    content: "This project will create designated dog-friendly zones in Princes Street Gardens...",
    estimatedCost: "£55,000",
    benefits: ["Improved pet amenities", "Safer spaces for dogs", "Enhances community experience"],
    votes: 982
  },
  {

    title: "Solar Panels for Craigmillar Community Centre",
    location: "Craigmillar, Edinburgh",
    district: "South-East",
    author: "Eleanor MacKenzie",
    dateSubmitted: "2024-01-23",
    category: "Sustainability",
    excerpt: "Installing solar panels on Craigmillar Community Centre...",
    content: "This project aims to install solar panels on the roof of Craigmillar Community Centre...",
    estimatedCost: "£50,000",
    benefits: ["Reduced energy costs", "Promotes renewable energy", "Long-term sustainability"],
    votes: 1125
  },
{
    title: "Expansion of Victoria Park Allotments",
    location: "Victoria Park, Edinburgh",
    district: "North-West",
    author: "Andrew Scott",
    dateSubmitted: "2024-01-26",
    category: "Green Space Development",
    excerpt: "Expanding the allotment plots in Victoria Park...",
    content: "Victoria Park’s allotment spaces have long been popular...",
    estimatedCost: "£35,000",
    benefits: ["Promotes local food production", "Encourages sustainability", "Builds community"],
    votes: 972
  },
  {
    title: "Bike Storage Hubs in Marchmont",
    location: "Marchmont, Edinburgh",
    district: "South-East",
    author: "Rebecca Ross",
    dateSubmitted: "2024-02-02",
    category: "Transportation Infrastructure",
    excerpt: "Installing secure bike storage hubs in Marchmont...",
    content: "This project proposes the installation of several secure bike storage hubs across Marchmont...",
    estimatedCost: "£70,000",
    benefits: ["Encourages cycling", "Reduces bike theft", "Promotes green transport"],
    votes: 1104
  },
  {
    title: "Tree Planting Initiative in Braid Hills",
    location: "Braid Hills, Edinburgh",
    district: "South-West",
    author: "Gavin Wallace",
    dateSubmitted: "2024-02-09",
    category: "Environmental Conservation",
    excerpt: "Planting 500 new trees in Braid Hills...",
    content: "This project focuses on planting 500 native trees across Braid Hills...",
    estimatedCost: "£30,000",
    benefits: ["Improves air quality", "Supports biodiversity", "Prevents erosion"],
    votes: 1241
  },
  {
    title: "Upgrade of Tollcross Sports Centre",
    location: "Tollcross, Edinburgh",
    district: "South-West",
    author: "Rachel McLean",
    dateSubmitted: "2024-01-30",
    category: "Sports Facility",
    excerpt: "Upgrading the facilities at Tollcross Sports Centre...",
    content: "This project proposes a major upgrade to the Tollcross Sports Centre...",
    estimatedCost: "£200,000",
    benefits: ["Modern facilities", "Increased accessibility", "Encourages healthy living"],
    votes: 1378
  },

  {
    title: "Public Wi-Fi Installation in Morningside",
    location: "Morningside, Edinburgh",
    district: "South-West",
    author: "Matthew Kerr",
    dateSubmitted: "2024-01-25",
    category: "Technology Infrastructure",
    excerpt: "Installing free public Wi-Fi in Morningside...",
    content: "This project will install free public Wi-Fi in key areas of Morningside...",
    estimatedCost: "£65,000",
    benefits: ["Improves digital access", "Supports local businesses", "Attracts visitors"],
    votes: 1043
  },
  {
    title: "Community Sports Hub in Newhaven",
    location: "Newhaven, Edinburgh",
    district: "North-East",
    author: "Liam Duncan",
    dateSubmitted: "2024-02-15",
    category: "Sports Facility",
    excerpt: "Building a community sports hub in Newhaven to encourage local participation in team sports and fitness activities.",
    content: "This project aims to establish a community sports hub in Newhaven, providing facilities for football, basketball, and fitness classes. The hub will cater to people of all ages, promoting physical health and social engagement.",
    estimatedCost: "£90,000",
    benefits: ["Promotes physical health", "Engages local community", "Provides free sports facilities"],
    votes: 1102
  },
  {
    title: "Renovation of Seafield Beachfront",
    location: "Seafield, Edinburgh",
    district: "North-East",
    author: "Emily Fraser",
    dateSubmitted: "2024-02-18",
    category: "Public Space Improvement",
    excerpt: "Improving Seafield’s beachfront with new seating areas, walking paths, and litter management solutions.",
    content: "The project aims to revitalize Seafield’s beachfront, adding new benches, walking paths, and litter management to create a more attractive and accessible space for both locals and visitors.",
    estimatedCost: "£120,000",
    benefits: ["Improves public space", "Attracts tourists", "Promotes environmental responsibility"],
    votes: 1054
  },
  {

    title: "Upgrade of Leith Theatre",
    location: "Leith, Edinburgh",
    district: "North-East",
    author: "Sophie Ramsay",
    dateSubmitted: "2024-02-20",
    category: "Cultural Infrastructure",
    excerpt: "Upgrading Leith Theatre with modern sound and lighting equipment for community performances.",
    content: "Leith Theatre is in need of modern sound and lighting systems. This project will ensure the venue continues to support community events, performances, and cultural programs.",
    estimatedCost: "£200,000",
    benefits: ["Supports local culture", "Enhances performance quality", "Attracts more visitors"],
    votes: 1260
  },
  {
    title: "Green Roofs Initiative in Leith Docks",
    location: "Leith Docks, Edinburgh",
    district: "North-East",
    author: "Daniel Johnston",
    dateSubmitted: "2024-02-17",
    category: "Sustainability",
    excerpt: "Introducing green roofs in Leith Docks to improve environmental sustainability and urban biodiversity.",
    content: "This project proposes the installation of green roofs on industrial buildings at Leith Docks. Green roofs will improve air quality, support local wildlife, and reduce energy consumption by providing insulation.",
    estimatedCost: "£75,000",
    benefits: ["Improves air quality", "Supports urban biodiversity", "Reduces energy costs"],
    votes: 980
  },
  {
    title: "Creation of a Public Park in Granton",
    location: "Granton, Edinburgh",
    district: "North-East",
    author: "Fiona Wallace",
    dateSubmitted: "2024-02-19",
    category: "Green Space Development",
    excerpt: "Transforming unused land in Granton into a public park with walking paths, a playground, and community spaces.",
    content: "This project will create a new public park in Granton, turning vacant land into green space with walking paths, a playground, and seating areas. It will provide a much-needed recreational space for local residents.",
    estimatedCost: "£100,000",
    benefits: ["Promotes outdoor activities", "Enhances neighborhood aesthetics", "Builds community"],
    votes: 1125
  },
  {
    title: "Expansion of Roseburn Path for Cyclists and Pedestrians",
    location: "Roseburn, Edinburgh",
    district: "North-West",
    author: "Tom Hamilton",
    dateSubmitted: "2024-02-12",
    category: "Transportation Infrastructure",
    excerpt: "Expanding the Roseburn Path to better accommodate cyclists and pedestrians, ensuring safety for all users.",
    content: "This project proposes expanding the Roseburn Path to create separate lanes for cyclists and pedestrians. The improvements will reduce conflicts between users and encourage more people to use the path for commuting and leisure.",
    estimatedCost: "£60,000",
    benefits: ["Improves safety", "Encourages cycling", "Promotes eco-friendly transport"],
    votes: 1140
  },
  {
    title: "Granton Youth Centre Renovation",
    location: "Granton, Edinburgh",
    district: "North-West",
    author: "Katherine Bell",
    dateSubmitted: "2024-02-16",
    category: "Youth Facility",
    excerpt: "Renovating Granton Youth Centre to provide modern facilities for educational and recreational activities.",
    content: "Granton Youth Centre is due for renovation, and this project will update the space with modern facilities, including a new study room, music studio, and recreational area. The renovation will ensure the centre continues to serve as a safe and productive space for young people.",
    estimatedCost: "£85,000",
    benefits: ["Engages local youth", "Provides educational support", "Safe recreational space"],
    votes: 1193
  },
  {
    title: "Water Sports Centre in Cramond",
    location: "Cramond, Edinburgh",
    district: "North-West",
    author: "Jamie Stewart",
    dateSubmitted: "2024-02-14",
    category: "Sports Facility",
    excerpt: "Developing a water sports centre in Cramond for kayaking, rowing, and sailing enthusiasts.",
    content: "This project will establish a water sports centre on the Cramond waterfront, providing facilities for kayaking, rowing, and sailing. The centre will offer lessons and equipment rentals, making water sports accessible to the local community.",
    estimatedCost: "£150,000",
    benefits: ["Encourages water sports", "Promotes outdoor activity", "Attracts visitors to the area"],
    votes: 1108
  },
  {
    title: "Eco-Friendly Bus Shelters in South Gyle",
    location: "South Gyle, Edinburgh",
    district: "South-West",
    author: "Oliver Mitchell",
    dateSubmitted: "2024-02-13",
    category: "Sustainability",
    excerpt: "Installing eco-friendly bus shelters with solar panels and green roofs in South Gyle.",
    content: "This project will install modern, eco-friendly bus shelters in South Gyle, equipped with solar panels for lighting and green roofs to reduce heat and absorb rainwater. These shelters will be both functional and environmentally sustainable.",
    estimatedCost: "£45,000",
    benefits: ["Promotes sustainability", "Improves public transport facilities", "Reduces energy usage"],
    votes: 1047
  },
  {
    title: "Upgrade of Saughton Park Rose Gardens",
    location: "Saughton Park, Edinburgh",
    district: "South-West",
    author: "Charlotte Reid",
    dateSubmitted: "2024-02-11",
    category: "Green Space Development",
    excerpt: "Restoring and upgrading the historic Rose Gardens in Saughton Park to enhance their beauty and accessibility.",
    content: "This project focuses on the restoration and upgrade of the Rose Gardens in Saughton Park. It will involve planting new varieties of roses, improving walkways, and adding accessible paths for those with mobility challenges.",
    estimatedCost: "£70,000",
    benefits: ["Enhances park aesthetics", "Improves accessibility", "Preserves local heritage"],
    votes: 1025
  }
];

export default mockProjects;
